"""IR → TypeScript code generation."""

from __future__ import annotations

import json
import keyword
import re
import textwrap
from collections.abc import Iterable
from pathlib import Path
from typing import Any, cast

from dyadpy._idents import to_camel as _to_camel
from dyadpy.ir import AppIR, ParamIR, RouteIR

HEADER_BANNER = """// AUTO-GENERATED by `dyadpy`. Do not edit by hand. Re-run `dyadpy dev`.
//
// Tour:
//   • api               — the typed client. `api.getIssue({ issueId: 1 })`.
//   • Domain types      — Issue, User, … Use directly in your own state/props.
//   • Errors            — discriminated on `kind`; switch on `.error.kind`.
//   • Enum consts       — `IssueStatus.Closed` instead of `"closed"` literals.
//   • Routes.X.{Args, Data, Error, Return}
//                       — per-route type aliases for helpers that need to
//                         reference a specific route's shape without retyping
//                         its unions by hand.

"""

# Matches the project's oxfmt line-width.
_INLINE_FIELDS = 3
_INLINE_LINE_BUDGET = 100
_INLINE_UNION_TERMS = 3
_DIVIDER_WIDTH = 78


def _render_header(ir: AppIR) -> str:
    # Streaming routes signal errors as SSE `event: error` frames, not as Result
    # envelopes — so `Result` is only imported when at least one unary route raises.
    type_imports = ["CallOptions", "ClientConfig", "RouteDescriptor"]
    if any(route.raises and not route.streams for route in ir.routes):
        type_imports.insert(1, "Result")
    return (
        HEADER_BANNER
        + 'import { createClient } from "@dyadpy/ts";\n'
        + f'import type {{ {", ".join(type_imports)} }} from "@dyadpy/ts";\n'
    )


def _section(title: str) -> str:
    """Emit a clean section heading: `// ── title ───────…`."""
    fill = max(3, _DIVIDER_WIDTH - len(title) - 6)
    return f"\n// ── {title} {'─' * fill}\n\n"


def render(ir: AppIR) -> str:
    _check_route_name_collisions(ir)
    parts: list[str] = [_render_header(ir)]

    name_map = _disambiguate(ir.components.keys())
    route_names = _route_ts_names(ir)
    error_names = {e.name for r in ir.routes for e in r.raises}

    domain_keys = sorted(k for k in ir.components if name_map[k] not in error_names)
    error_keys = sorted(k for k in ir.components if name_map[k] in error_names)

    if domain_keys:
        parts.append(_section("Domain types"))
        parts.append(_render_components(domain_keys, ir, name_map))

    if error_keys:
        parts.append(_section("Errors"))
        parts.append(_render_components(error_keys, ir, name_map))

    enum_block = _render_enum_consts(ir, name_map)
    if enum_block:
        parts.append(_section("Enum value-objects"))
        parts.append(enum_block)

    parts.append(_section("Client"))
    parts.append(_render_api_interface(ir, name_map, route_names))
    parts.append("\n")
    parts.append(_render_route_table(ir, route_names))
    parts.append(
        '\nexport type ApiClientOptions = Omit<ClientConfig, "routes">;\n\n'
        "export function createApi(options: ApiClientOptions = {}): ApiRoutes {\n"
        "  return createClient({ ...options, routes: _routes }) as ApiRoutes;\n"
        "}\n\n"
        "export const api = createApi();\n",
    )

    namespace = _render_routes_namespace(ir, name_map, route_names)
    if namespace:
        parts.append(_section("Per-route type aliases"))
        parts.append(namespace)
    return "".join(parts)


def _render_components(keys: list[str], ir: AppIR, name_map: dict[str, str]) -> str:
    chunks: list[str] = []
    for raw in keys:
        schema = ir.components[raw]
        ts_name = name_map[raw]
        doc = _jsdoc(_type_doc(schema, ts_name), indent="")
        body = _render_type(schema, name_map, indent="")
        chunks.append(f"{doc}export type {ts_name} = {body};\n")
    return "\n".join(chunks)


def _type_doc(schema: dict[str, Any], ts_name: str) -> str | None:
    # msgspec auto-emits `title: "<ClassName>"` for every Struct; ignore it,
    # surface only a real docstring (which lands in `description`).
    desc = schema.get("description")
    if isinstance(desc, str) and desc.strip():
        return desc
    title = schema.get("title")
    if isinstance(title, str) and title.strip() and title != ts_name:
        return title
    return None


def _render_api_interface(
    ir: AppIR,
    name_map: dict[str, str],
    route_names: dict[int, str],
) -> str:
    lines = ["export interface ApiRoutes {\n"]
    for i, route in enumerate(ir.routes):
        if i > 0:
            lines.append("\n")
        if route.description:
            lines.append(_jsdoc(route.description, indent="  "))
        lines.append("  " + _render_method_signature(route, name_map, route_names[i]) + "\n")
    lines.append("}\n")
    return "".join(lines)


def _render_route_table(ir: AppIR, route_names: dict[int, str]) -> str:
    lines = ["const _routes: ReadonlyArray<RouteDescriptor> = [\n"]
    for i, route in enumerate(ir.routes):
        lines.append(_render_route_descriptor(route, route_names[i], indent="  ") + ",\n")
    lines.append("];\n")
    return "".join(lines)


def _render_enum_consts(ir: AppIR, name_map: dict[str, str]) -> str:
    # `kind` is the msgspec tag discriminator — skipped intentionally so the
    # union narrowing on `kind` stays as a string-literal, not a value-object lookup.
    type_names = set(name_map.values())
    used: set[str] = set()
    consts: list[str] = []
    for raw in sorted(ir.components):
        props_any: Any = ir.components[raw].get("properties")
        if not isinstance(props_any, dict):
            continue
        props = cast("dict[str, Any]", props_any)
        struct_name = name_map.get(raw, _safe_ident(raw))
        for field_name, schema in props.items():
            if field_name == "kind" or not isinstance(schema, dict):
                continue
            values_any: Any = cast("dict[str, Any]", schema).get("enum")
            if not isinstance(values_any, list):
                continue
            values = cast("list[Any]", values_any)  # type: ignore[redundant-cast]
            if not all(isinstance(v, str) for v in values):
                continue
            str_values = cast("list[str]", values)
            entries = ", ".join(f"{_pascal(v)}: {json.dumps(v)}" for v in str_values)
            base = struct_name + _pascal(field_name)
            const_name = _unique_enum_name(base, type_names, used)
            used.add(const_name)
            consts.append(f"export const {const_name} = {{ {entries} }} as const;\n")
    return "\n".join(consts)


def _unique_enum_name(base: str, type_names: set[str], used: set[str]) -> str:
    if base not in type_names and base not in used and not _is_reserved(base):
        return base
    suffixed = f"{base}Enum"
    if suffixed not in type_names and suffixed not in used and not _is_reserved(suffixed):
        return suffixed
    i = 2
    while True:
        candidate = f"{suffixed}_{i}"
        if candidate not in type_names and candidate not in used:
            return candidate
        i += 1


def _render_routes_namespace(
    ir: AppIR,
    name_map: dict[str, str],
    route_names: dict[int, str],
) -> str:
    if not ir.routes:
        return ""
    out = ["export namespace Routes {\n"]
    for i, route in enumerate(ir.routes):
        if i > 0:
            out.append("\n")
        out.append(f"  export namespace {route_names[i]} {{\n")

        args_type, _ = _render_args_type(route.params, name_map, indent="    ")
        if args_type:
            out.append(f"    export type Args = {args_type};\n")

        if route.streams:
            event = (
                _render_type(route.event_schema, name_map, indent="    ")
                if route.event_schema
                else "unknown"
            )
            out.append(f"    export type Event = {event};\n")
            out.append("    export type Return = AsyncIterable<Event>;\n")
        else:
            data = (
                _render_type(route.response, name_map, indent="    ") if route.response else "void"
            )
            out.append(f"    export type Data = {data};\n")
            if route.raises:
                err = _render_error_union(route.raises, name_map, indent="    ")
                out.append(f"    export type Error = {err};\n")
                out.append("    export type Return = Promise<Result<Data, Error>>;\n")
            else:
                out.append("    export type Return = Promise<Data>;\n")

        out.append("  }\n")
    out.append("}\n")
    return "".join(out)


# Names that must not appear as top-level type aliases or const declarations.
_TS_RESERVED_TYPE_NAMES = frozenset(
    {
        "break",
        "case",
        "catch",
        "class",
        "const",
        "continue",
        "debugger",
        "default",
        "delete",
        "do",
        "else",
        "enum",
        "export",
        "extends",
        "false",
        "finally",
        "for",
        "function",
        "if",
        "import",
        "in",
        "instanceof",
        "let",
        "new",
        "null",
        "return",
        "super",
        "switch",
        "this",
        "throw",
        "true",
        "try",
        "typeof",
        "var",
        "void",
        "while",
        "with",
        "yield",
        # TS built-in type names and ambient globals worth protecting.
        "any",
        "boolean",
        "number",
        "string",
        "bigint",
        "symbol",
        "object",
        "undefined",
        "never",
        "unknown",
        "Object",
        "Function",
        "Array",
        "Promise",
        "Date",
        "Error",
        "Map",
        "Set",
        "RegExp",
        "JSON",
        "Math",
        "Result",
        "CallOptions",
        "RouteDescriptor",
        "Routes",
        "api",
    }
)


def _disambiguate(raw_keys: Iterable[str]) -> dict[str, str]:
    keys = list(raw_keys)
    by_short: dict[str, list[str]] = {}
    for k in keys:
        short = k.rsplit(".", 1)[-1]
        by_short.setdefault(short, []).append(k)

    out: dict[str, str] = {}
    for short, members in by_short.items():
        if len(members) == 1:
            full = members[0]
            if _is_reserved(short):
                renamed = _module_prefixed(full)
                out[full] = renamed if renamed != _safe_ident(short) else _safe_ident(short) + "_"
            else:
                out[full] = _safe_ident(short)
            continue
        for full in members:
            out[full] = _module_prefixed(full)

    seen: dict[str, int] = {}
    for raw in keys:
        candidate = out[raw]
        if candidate not in seen:
            seen[candidate] = 1
            continue
        seen[candidate] += 1
        out[raw] = f"{candidate}_{seen[candidate]}"
    return out


def _is_reserved(name: str) -> bool:
    return name in _TS_RESERVED_TYPE_NAMES


def _check_route_name_collisions(ir: AppIR) -> None:
    # Different Python names that camelCase to the same method name are ambiguous.
    # Exact duplicates are valid for file routers and are disambiguated below.
    seen: dict[str, str] = {}
    for route in ir.routes:
        camel = _to_camel(route.name)
        prior = seen.get(camel)
        if prior is not None and prior != route.name:
            raise ValueError(
                f"Dyadpy: routes {prior!r} and {route.name!r} both produce the TS "
                f"method name {camel!r}. Rename one of the Python handlers to "
                "disambiguate before regenerating.",
            )
        seen[camel] = route.name


def _route_ts_names(ir: AppIR) -> dict[int, str]:
    base_names = [_safe_ident(_to_camel(route.name)) for route in ir.routes]
    counts: dict[str, int] = {}
    for name in base_names:
        counts[name] = counts.get(name, 0) + 1

    used: set[str] = set()
    out: dict[int, str] = {}
    for i, route in enumerate(ir.routes):
        base = base_names[i]
        candidate = base if counts[base] == 1 else _path_qualified_route_name(route)
        candidate = _unique_route_name(candidate, used)
        used.add(candidate)
        out[i] = candidate
    return out


def _path_qualified_route_name(route: RouteIR) -> str:
    parts = _route_path_parts(route.path)
    stem = _to_camel("_".join(parts)) if parts else "root"
    return _safe_ident(stem + _pascal(route.name))


def _route_path_parts(path: str) -> list[str]:
    return [part for part in re.split(r"[^0-9A-Za-z]+", path) if part]


def _unique_route_name(candidate: str, used: set[str]) -> str:
    if candidate not in used and not _is_reserved(candidate):
        return candidate
    base = candidate if not _is_reserved(candidate) else f"{candidate}_"
    i = 2
    while True:
        suffixed = f"{base}_{i}"
        if suffixed not in used:
            return suffixed
        i += 1


def _module_prefixed(full_key: str) -> str:
    head, _, tail = full_key.rpartition(".")
    prefix = head.rsplit(".", 1)[-1] if head else ""
    return _safe_ident(_pascal(prefix) + tail) if prefix else _safe_ident(tail)


def _pascal(name: str) -> str:
    return "".join(
        part[:1].upper() + part[1:] for part in name.replace("-", "_").split("_") if part
    )


def write(ir: AppIR, out: Path) -> None:
    # Atomic: tmp + rename so the TS toolchain never reads a partial file.
    tmp = out.with_suffix(out.suffix + ".tmp")
    tmp.parent.mkdir(parents=True, exist_ok=True)
    tmp.write_text(render(ir), encoding="utf-8")
    tmp.replace(out)


# ---- type rendering ----


def _render_type(
    schema: Any,
    name_map: dict[str, str] | None = None,
    *,
    indent: str = "",
) -> str:
    if schema is None:
        return "void"
    if not isinstance(schema, dict):
        return "unknown"
    s = cast("dict[str, Any]", schema)

    if "$ref" in s:
        raw = str(s["$ref"]).rsplit("/", 1)[-1]
        if name_map is not None and raw in name_map:
            return name_map[raw]
        return _safe_ident(raw)
    if "const" in s:
        return json.dumps(s["const"])
    if "enum" in s:
        return _render_union([json.dumps(v) for v in cast("list[Any]", s["enum"])], indent=indent)
    if "oneOf" in s:
        return _render_union(
            [_render_type(x, name_map, indent=indent) for x in s["oneOf"]],
            indent=indent,
        )
    if "anyOf" in s:
        return _render_union(
            [_render_type(x, name_map, indent=indent) for x in s["anyOf"]],
            indent=indent,
        )
    if "allOf" in s:
        return " & ".join(_render_type(x, name_map, indent=indent) for x in s["allOf"])

    t: Any = s.get("type")
    if isinstance(t, list):
        # Pylance flags list contents as Unknown without the cast; mypy thinks
        # the cast is redundant. Side with Pylance — it's what shows in the editor.
        ts = cast("list[Any]", t)  # type: ignore[redundant-cast]
        rest = {k: v for k, v in s.items() if k != "type"}
        return _render_union(
            [_render_type({"type": x, **rest}, name_map, indent=indent) for x in ts],
            indent=indent,
        )

    if t == "string":
        return "Blob" if s.get("format") == "binary" else "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        if "prefixItems" in s:
            return (
                "["
                + ", ".join(_render_type(x, name_map, indent=indent) for x in s["prefixItems"])
                + "]"
            )
        items = s.get("items")
        inner = _render_type(items, name_map, indent=indent) if items else "unknown"
        return f"Array<{inner}>"
    if t == "object" or "properties" in s or "additionalProperties" in s:
        props = cast("dict[str, Any]", s.get("properties") or {})
        required_raw = cast("list[Any]", s.get("required") or [])
        required: set[str] = {_to_camel(str(k)) for k in required_raw}
        additional = s.get("additionalProperties")
        if not props and additional is not None and additional is not False:
            return f"Record<string, {_render_type(additional, name_map, indent=indent)}>"
        if not props:
            return "Record<string, never>"
        return _render_object(props, required, name_map, indent=indent)

    return "unknown"


def _render_object(
    props: dict[str, Any],
    required: set[str],
    name_map: dict[str, str] | None,
    *,
    indent: str,
) -> str:
    inner_indent = indent + "  "
    field_strs: list[tuple[str, str]] = []  # (jsdoc_or_empty, "key: type")
    for key, child in props.items():
        ts_key = _to_camel(str(key))
        opt = "" if ts_key in required else "?"
        rendered = _render_type(child, name_map, indent=inner_indent)
        line = f"{_safe_key(ts_key)}{opt}: {rendered}"
        doc_source = _field_doc(child)
        field_strs.append((doc_source, line))

    inline_candidate = "{ " + "; ".join(line for _, line in field_strs) + " }"
    if (
        len(field_strs) <= _INLINE_FIELDS
        and all(doc == "" for doc, _ in field_strs)
        and len(indent) + len(inline_candidate) <= _INLINE_LINE_BUDGET
        and "\n" not in inline_candidate
    ):
        return inline_candidate

    lines = ["{"]
    for doc, line in field_strs:
        if doc:
            lines.append(_jsdoc(doc, indent=inner_indent).rstrip("\n"))
        lines.append(f"{inner_indent}{line};")
    lines.append(f"{indent}}}")
    return "\n".join(lines)


def _render_union(terms: list[str], *, indent: str) -> str:
    """Inline ``A | B | C`` for short unions; multi-line for long ones."""
    inline = " | ".join(terms)
    if (
        len(terms) <= _INLINE_UNION_TERMS
        and len(indent) + len(inline) <= _INLINE_LINE_BUDGET
        and "\n" not in inline
    ):
        return inline
    inner = indent + "  "
    return "\n" + "\n".join(f"{inner}| {t}" for t in terms)


def _field_doc(schema: Any) -> str:
    if not isinstance(schema, dict):
        return ""
    s = cast("dict[str, Any]", schema)
    desc = s.get("description")
    return str(desc) if isinstance(desc, str) and desc.strip() else ""


def _render_method_signature(route: RouteIR, name_map: dict[str, str], route_name: str) -> str:
    args_type, args_optional = _render_args_type(route.params, name_map, indent="  ")
    return_type = _render_return_type(route, name_map)
    if args_type is None:
        return f"{route_name}(opts?: CallOptions): {return_type};"

    inline = (
        f"{route_name}(args{'?' if args_optional else ''}: {args_type}, opts?: CallOptions): "
        f"{return_type};"
    )
    if "\n" not in inline and len(inline) <= _INLINE_LINE_BUDGET:
        return inline

    indented_args = textwrap.indent(args_type, "  ").lstrip()
    return (
        f"{route_name}(\n"
        f"    args{'?' if args_optional else ''}: {indented_args},\n"
        f"    opts?: CallOptions,\n"
        f"  ): {return_type};"
    )


def _render_args_type(
    params: list[ParamIR],
    name_map: dict[str, str],
    *,
    indent: str,
) -> tuple[str | None, bool]:
    if not params:
        return None, True
    props: dict[str, Any] = {}
    required: set[str] = set()
    all_optional = True
    for p in params:
        if p.required:
            all_optional = False
        ts_name = _to_camel(p.name)
        if p.required:
            required.add(ts_name)
        props[ts_name] = p.schema
    return _render_object(props, required, name_map, indent=indent), all_optional


def _render_return_type(route: RouteIR, name_map: dict[str, str]) -> str:
    if route.streams:
        event = (
            _render_type(route.event_schema, name_map, indent="  ")
            if route.event_schema
            else "unknown"
        )
        return f"AsyncIterable<{event}>"
    data = _render_type(route.response, name_map, indent="  ") if route.response else "void"
    if route.raises:
        err = _render_error_union(route.raises, name_map, indent="  ")
        return f"Promise<Result<{data}, {err}>>"
    return f"Promise<{data}>"


def _render_error_union(raises: list[Any], name_map: dict[str, str], *, indent: str) -> str:
    return _render_union(
        [name_map.get(e.name, _safe_ident(e.name)) for e in raises],
        indent=indent,
    )


def _render_route_descriptor(route: RouteIR, route_name: str, *, indent: str) -> str:
    parts = [
        f"method: {json.dumps(route.method)}",
        f"path: {json.dumps(route.path)}",
        f"name: {json.dumps(route_name)}",
    ]
    if route.params:
        parts.append(_render_param_descriptor_list(route.params, indent=indent))
    if route.streams:
        parts.append("streams: true")
    if route.raises:
        parts.append("result: true")
    if route.binary_body:
        parts.append("binaryBody: true")
    if route.binary_response:
        parts.append("binaryResponse: true")
    if route.form_body:
        parts.append("formBody: true")

    inline = indent + "{ " + ", ".join(parts) + " }"
    if "\n" not in inline and len(inline) <= _INLINE_LINE_BUDGET:
        return inline

    inner = indent + "  "
    lines = [indent + "{"]
    for p in parts:
        lines.append(f"{inner}{p},")
    lines.append(indent + "}")
    return "\n".join(lines)


def _render_param_descriptor_list(params: list[ParamIR], *, indent: str) -> str:
    # `indent` is the outer descriptor's indent; `params:` sits one nesting in.
    items = [_render_param_descriptor(p) for p in params]
    inline = "params: [" + ", ".join(items) + "]"
    if len(indent) + 2 + len(inline) <= _INLINE_LINE_BUDGET:
        return inline
    item_indent = indent + "    "
    close_indent = indent + "  "
    return (
        "params: [\n" + ",\n".join(f"{item_indent}{item}" for item in items) + f",\n{close_indent}]"
    )


def _render_param_descriptor(p: ParamIR) -> str:
    parts = [
        f"name: {json.dumps(_to_camel(p.name))}",
        f"alias: {json.dumps(p.alias)}",
        f"in: {json.dumps(p.location)}",
    ]
    if p.embed:
        parts.append("embed: true")
    return "{ " + ", ".join(parts) + " }"


def _jsdoc(text: Any, *, indent: str) -> str:
    if not text or not isinstance(text, str):
        return ""
    cleaned = text.strip()
    if not cleaned:
        return ""
    lines = cleaned.splitlines()
    if len(lines) == 1:
        return f"{indent}/** {lines[0]} */\n"
    out = [f"{indent}/**"]
    for line in lines:
        if line:
            out.append(f"{indent} * {line}")
        else:
            out.append(f"{indent} *")
    out.append(f"{indent} */")
    return "\n".join(out) + "\n"


_IDENT_RE = re.compile(r"[^A-Za-z0-9_]")
_SAFE_KEY_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _safe_ident(name: str) -> str:
    cleaned = _IDENT_RE.sub("_", name)
    if cleaned and cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned or "_"


def _safe_key(key: str) -> str:
    if _SAFE_KEY_RE.match(key) and not keyword.iskeyword(key):
        return key
    return json.dumps(key)
