"""IR → TypeScript code generation."""

from __future__ import annotations

import json
import keyword
import re
import shutil
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any, TypedDict, cast

from dyadpy._idents import to_camel as _to_camel
from dyadpy.ir import AppIR, ParamIR, RouteIR

HEADER_BANNER = """// @ts-nocheck
/* eslint-disable */
// biome-ignore-all lint: generated dyadpy client
// AUTO-GENERATED by `dyadpy`. Do not edit by hand. Re-run `dyadpy dev`.

"""

JSON_TYPE_ALIASES = """export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonObject | JsonValue[];
export type JsonObject = { [key: string]: JsonValue };
"""

# Matches the project's oxfmt line-width.
_INLINE_FIELDS = 3
_INLINE_LINE_BUDGET = 100
_INLINE_UNION_TERMS = 3


def _render_types_header(ir: AppIR) -> str:
    type_imports = ["CallOptions"]
    if any(route.raises and not route.streams for route in ir.routes):
        type_imports.append("Result")
    return HEADER_BANNER + f'import type {{ {", ".join(type_imports)} }} from "@dyadpy/ts";\n'


def _section() -> str:
    return "\n"


@dataclass(frozen=True, slots=True)
class _RenderState:
    ir: AppIR
    name_map: dict[str, str]
    route_names: dict[int, str]
    route_tree: _NamespaceNode
    domain_keys: list[str]
    error_keys: list[str]


def _build_state(ir: AppIR) -> _RenderState:
    _check_route_name_collisions(ir)
    name_map = _disambiguate(ir.components.keys())
    route_names = _route_ts_names(ir)
    route_tree = _route_namespace_tree(ir, route_names)
    error_names = {e.name for r in ir.routes for e in r.raises}
    domain_keys = sorted(k for k in ir.components if name_map[k] not in error_names)
    error_keys = sorted(k for k in ir.components if name_map[k] in error_names)
    return _RenderState(
        ir=ir,
        name_map=name_map,
        route_names=route_names,
        route_tree=route_tree,
        domain_keys=domain_keys,
        error_keys=error_keys,
    )


def render(ir: AppIR) -> dict[str, str]:
    """Render the optimized folder client.

    The generated public entry stays tiny. Heavy declaration output lives in
    ``types.d.ts`` and full route descriptors live in lazily imported route
    chunks under ``routes/``.
    """
    state = _build_state(ir)
    files: dict[str, str] = {
        "index.ts": _render_index(state),
        "types.d.ts": _render_types_file(state),
        "meta.ts": _render_meta_file(state),
    }
    files.update(_render_route_files(state))
    return files


def _render_types_file(state: _RenderState) -> str:
    ir = state.ir
    name_map = state.name_map
    parts: list[str] = [_render_types_header(ir)]

    if state.domain_keys:
        parts.append(_section())
        parts.append(_render_components(state.domain_keys, ir, name_map))

    if state.error_keys:
        parts.append(_section())
        parts.append(_render_components(state.error_keys, ir, name_map))

    if _uses_json_types(ir):
        parts.append(_section())
        parts.append(JSON_TYPE_ALIASES)

    parts.append(_section())
    parts.append(_render_api_interface(ir, name_map, state.route_tree))

    namespace = _render_routes_namespace(ir, name_map, state.route_names)
    if namespace:
        parts.append(_section())
        parts.append(namespace)
    return "".join(parts)


def _render_index(state: _RenderState) -> str:
    return (
        HEADER_BANNER
        + 'import { createLazyClient } from "@dyadpy/ts";\n'
        + 'import type { LazyClientConfig } from "@dyadpy/ts";\n'
        + 'import { routeMeta } from "./meta";\n'
        + 'import { loadRoute } from "./routes";\n'
        + 'import type { ApiRoutes } from "./types";\n\n'
        + 'export type * from "./types";\n'
        + 'export { routeMeta } from "./meta";\n\n'
        + 'export type ApiClientOptions = Omit<LazyClientConfig, "routeMeta" | "loadRoute">;\n\n'
        + "export function createApi(options: ApiClientOptions = {}): ApiRoutes {\n"
        + "  return createLazyClient<ApiRoutes>({ ...options, routeMeta, loadRoute });\n"
        + "}\n\n"
        + "export const api = createApi();\n"
    )


def _render_meta_file(state: _RenderState) -> str:
    entries_by_index = _flatten_namespace_entries(state.route_tree)
    lines = [
        HEADER_BANNER,
        'import type { RouteMeta } from "@dyadpy/ts";\n\n',
        "export const routeMeta: ReadonlyArray<RouteMeta> = [\n",
    ]
    for i, route in enumerate(state.ir.routes):
        lines.append(
            _render_route_meta(route, state.route_names[i], entries_by_index[i], indent="  ")
            + ",\n",
        )
    lines.append("];\n")
    return "".join(lines)


def _render_route_files(state: _RenderState) -> dict[str, str]:
    entries_by_index = _flatten_namespace_entries(state.route_tree)
    chunk_names = _route_chunk_names(entries_by_index)
    routes_by_chunk: dict[str, list[int]] = {}
    for i in range(len(state.ir.routes)):
        routes_by_chunk.setdefault(chunk_names[i], []).append(i)

    files: dict[str, str] = {}

    # Emit one `import(...)` per chunk file rather than per route. With a route
    # per switch case, bundlers (Turbopack especially) track every call site as
    # a separate code-split computation in their persistent cache — a 1000-route
    # app produces ~1000 cache entries even though only ~dozens of unique chunks
    # exist. The route→chunk lookup table is a plain string map and stays cheap.
    unique_chunks = sorted(routes_by_chunk.keys())
    index_lines = [
        HEADER_BANNER,
        'import type { RouteDescriptor } from "@dyadpy/ts";\n\n',
        "const chunkLoaders: Record<string, () => Promise<Record<string, RouteDescriptor>>> = {\n",
    ]
    for chunk in unique_chunks:
        index_lines.append(
            f"  {json.dumps(chunk)}: () => import({json.dumps('./' + chunk)}),\n",
        )
    index_lines.append("};\n\n")

    index_lines.append("const routeChunks: Record<string, string> = {\n")
    for i in range(len(state.ir.routes)):
        route_name = state.route_names[i]
        chunk_name = chunk_names[i]
        index_lines.append(
            f"  {json.dumps(route_name)}: {json.dumps(chunk_name)},\n",
        )
    index_lines.append("};\n\n")

    index_lines.append(
        "export async function loadRoute(id: string): Promise<RouteDescriptor> {\n"
        "  const chunk = routeChunks[id];\n"
        "  if (chunk === undefined) throw new Error(`Unknown Dyadpy route: ${id}`);\n"
        "  const mod = await chunkLoaders[chunk]!();\n"
        "  const route = mod[id];\n"
        "  if (route === undefined) throw new Error(`Unknown Dyadpy route: ${id}`);\n"
        "  return route;\n"
        "}\n",
    )
    files["routes/index.ts"] = "".join(index_lines)

    for chunk_name, indexes in routes_by_chunk.items():
        lines = [
            HEADER_BANNER,
            'import type { RouteDescriptor } from "@dyadpy/ts";\n',
        ]
        for i in indexes:
            route = state.ir.routes[i]
            entry = entries_by_index[i]
            route_name = state.route_names[i]
            lines.append("\n")
            lines.append(
                f"export const {route_name}: RouteDescriptor = "
                f"{_render_route_descriptor(route, route_name, entry, indent='', components=state.ir.components)};\n",
            )
        files[f"routes/{chunk_name}.ts"] = "".join(lines)
    return files


def _render_components(keys: list[str], ir: AppIR, name_map: dict[str, str]) -> str:
    chunks: list[str] = []
    for raw in keys:
        schema = ir.components[raw]
        ts_name = name_map[raw]
        body = _render_type(schema, name_map, indent="")
        chunks.append(f"export type {ts_name} = {body};\n")
    return "\n".join(chunks)


class _NamespaceEntry(TypedDict):
    route_index: int
    segments: list[str]
    verb: str
    operation_name: str


class _NamespaceNode(TypedDict):
    children: dict[str, _NamespaceNode]
    leaves: dict[str, _NamespaceEntry]


def _new_namespace_node() -> _NamespaceNode:
    return {"children": {}, "leaves": {}}


def _render_api_interface(
    ir: AppIR,
    name_map: dict[str, str],
    route_tree: _NamespaceNode,
) -> str:
    lines = ["export interface ApiRoutes {\n"]
    lines.extend(_render_api_node(route_tree, ir, name_map, indent="  "))
    lines.append("}\n")
    return "".join(lines)


def _render_api_node(
    node: _NamespaceNode,
    ir: AppIR,
    name_map: dict[str, str],
    *,
    indent: str,
) -> list[str]:
    lines: list[str] = []
    for key, child in node["children"].items():
        lines.append(f"{indent}{_safe_key(key)}: {{\n")
        lines.extend(_render_api_node(child, ir, name_map, indent=indent + "  "))
        lines.append(f"{indent}}};\n")
    for key, entry in node["leaves"].items():
        route = ir.routes[entry["route_index"]]
        lines.append(f"{indent}{_render_method_signature(route, name_map, key, indent=indent)}\n")
    return lines


def _render_route_meta(
    route: RouteIR,
    route_name: str,
    namespace: _NamespaceEntry,
    *,
    indent: str,
) -> str:
    parts = [
        f"id: {json.dumps(route_name)}",
        f"name: {json.dumps(route_name)}",
        "segments: " + json.dumps(namespace["segments"]),
        f"verb: {json.dumps(namespace['verb'])}",
    ]
    if route.params:
        parts.append("hasArgs: true")
    if route.streams:
        parts.append("streams: true")
    inline = indent + "{ " + ", ".join(parts) + " }"
    if len(inline) <= _INLINE_LINE_BUDGET:
        return inline
    inner = indent + "  "
    lines = [indent + "{"]
    for p in parts:
        lines.append(f"{inner}{p},")
    lines.append(indent + "}")
    return "\n".join(lines)


def _route_chunk_names(entries_by_index: dict[int, _NamespaceEntry]) -> dict[int, str]:
    out: dict[int, str] = {}
    for i, entry in entries_by_index.items():
        raw = entry["segments"][0] if entry["segments"] else "root"
        out[i] = _safe_ident(raw.lower())
    return out


def _render_routes_namespace(
    ir: AppIR,
    name_map: dict[str, str],
    route_names: dict[int, str],
) -> str:
    if not ir.routes:
        return ""
    out = ["export namespace Routes {\n"]
    for i, route in enumerate(ir.routes):
        if i > 0:
            out.append("\n")
        out.append(f"  export namespace {route_names[i]} {{\n")

        args_type, _ = _render_args_type(route.params, name_map, indent="    ")
        if args_type:
            out.append(f"    export type Args = {args_type};\n")

        if route.streams:
            event = (
                _render_type(route.event_schema, name_map, indent="    ")
                if route.event_schema
                else "unknown"
            )
            out.append(f"    export type Event = {event};\n")
            out.append("    export type Return = AsyncIterable<Event>;\n")
        else:
            data = (
                _render_type(route.response, name_map, indent="    ") if route.response else "void"
            )
            out.append(f"    export type Data = {data};\n")
            if route.raises:
                err = _render_error_union(route.raises, name_map, indent="    ")
                out.append(f"    export type Error = {err};\n")
                out.append("    export type Return = Promise<Result<Data, Error>>;\n")
            else:
                out.append("    export type Return = Promise<Data>;\n")

        out.append("  }\n")
    out.append("}\n")
    return "".join(out)


# Names that must not appear as top-level type aliases or generated route symbols.
_TS_RESERVED_TYPE_NAMES = frozenset(
    {
        "break",
        "case",
        "catch",
        "class",
        "const",
        "continue",
        "debugger",
        "default",
        "delete",
        "do",
        "else",
        "enum",
        "export",
        "extends",
        "false",
        "finally",
        "for",
        "function",
        "if",
        "import",
        "in",
        "instanceof",
        "let",
        "new",
        "null",
        "return",
        "super",
        "switch",
        "this",
        "throw",
        "true",
        "try",
        "typeof",
        "var",
        "void",
        "while",
        "with",
        "yield",
        # TS built-in type names and ambient globals worth protecting.
        "any",
        "boolean",
        "number",
        "string",
        "bigint",
        "symbol",
        "object",
        "undefined",
        "never",
        "unknown",
        "Object",
        "Function",
        "Array",
        "Promise",
        "Date",
        "Error",
        "Map",
        "Set",
        "RegExp",
        "JSON",
        "Math",
        "Result",
        "CallOptions",
        "LazyClientConfig",
        "RouteDescriptor",
        "RouteMeta",
        "Routes",
        "JsonPrimitive",
        "JsonValue",
        "JsonObject",
        "api",
    }
)


def _disambiguate(raw_keys: Iterable[str]) -> dict[str, str]:
    keys = list(raw_keys)
    by_short: dict[str, list[str]] = {}
    for k in keys:
        short = k.rsplit(".", 1)[-1]
        by_short.setdefault(short, []).append(k)

    out: dict[str, str] = {}
    for short, members in by_short.items():
        if len(members) == 1:
            full = members[0]
            if _is_reserved(short):
                renamed = _module_prefixed(full)
                out[full] = renamed if renamed != _safe_ident(short) else _safe_ident(short) + "_"
            else:
                out[full] = _safe_ident(short)
            continue
        for full in members:
            out[full] = _module_prefixed(full)

    seen: dict[str, int] = {}
    for raw in keys:
        candidate = out[raw]
        if candidate not in seen:
            seen[candidate] = 1
            continue
        seen[candidate] += 1
        out[raw] = f"{candidate}_{seen[candidate]}"
    return out


def _is_reserved(name: str) -> bool:
    return name in _TS_RESERVED_TYPE_NAMES


def _check_route_name_collisions(ir: AppIR) -> None:
    # Different Python names that camelCase to the same method name are ambiguous.
    # Exact duplicates are valid for file routers and are disambiguated below.
    seen: dict[str, str] = {}
    for route in ir.routes:
        camel = _to_camel(route.name)
        prior = seen.get(camel)
        if prior is not None and prior != route.name:
            raise ValueError(
                f"Dyadpy: routes {prior!r} and {route.name!r} both produce the TS "
                f"method name {camel!r}. Rename one of the Python handlers to "
                "disambiguate before regenerating.",
            )
        seen[camel] = route.name


def _route_ts_names(ir: AppIR) -> dict[int, str]:
    base_names = [_safe_ident(_to_camel(route.name)) for route in ir.routes]
    counts: dict[str, int] = {}
    for name in base_names:
        counts[name] = counts.get(name, 0) + 1

    used: set[str] = set()
    out: dict[int, str] = {}
    for i, route in enumerate(ir.routes):
        base = base_names[i]
        candidate = base if counts[base] == 1 else _path_qualified_route_name(route)
        candidate = _unique_route_name(candidate, used)
        used.add(candidate)
        out[i] = candidate
    return out


def _path_qualified_route_name(route: RouteIR) -> str:
    parts = _route_path_parts(route.path)
    stem = _to_camel("_".join(parts)) if parts else "root"
    return _safe_ident(stem + _pascal(route.name))


def _route_path_parts(path: str) -> list[str]:
    return [part for part in re.split(r"[^0-9A-Za-z]+", path) if part]


_PARAM_TOKEN_RE = re.compile(r"\{[^}]+\}|\$[A-Za-z_][A-Za-z0-9_]*")


def _has_param_token(segment: str) -> bool:
    return _PARAM_TOKEN_RE.search(segment) is not None


def _literal_route_segments(path: str) -> list[str]:
    segments: list[str] = []
    for part in path.split("/"):
        if not part:
            continue
        literal = _PARAM_TOKEN_RE.sub(" ", part)
        for token in re.split(r"[^0-9A-Za-z]+", literal):
            if token:
                segments.append(_safe_ident(_to_camel(token)))
    return segments


def _route_ends_with_param(path: str) -> bool:
    parts = [part for part in path.split("/") if part]
    return bool(parts) and _has_param_token(parts[-1])


def _method_verb(method: str, ends_with_param: bool) -> str | None:
    m = method.upper()
    if m == "GET":
        return "byId" if ends_with_param else "list"
    if m == "POST":
        return None if ends_with_param else "create"
    if m in {"PATCH", "PUT"}:
        return "update"
    if m == "DELETE":
        return "delete"
    return None


def _split_camel(value: str) -> list[str]:
    spaced = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", value)
    return [part for part in spaced.lower().split(" ") if part]


def _lower_first(value: str) -> str:
    return value[:1].lower() + value[1:] if value else value


def _camel_case(parts: list[str]) -> str:
    return "".join(part if i == 0 else part[:1].upper() + part[1:] for i, part in enumerate(parts))


def _derive_verb(
    operation_name: str,
    namespace_tail: str | None,
    method: str,
    ends_with_param: bool,
) -> str:
    fallback = _method_verb(method, ends_with_param)
    if not namespace_tail:
        return fallback or operation_name

    parts = _split_camel(operation_name)
    if not parts:
        return fallback or operation_name

    tail = namespace_tail.lower()
    singular = tail[:-1] if tail.endswith("s") else tail
    last = parts[-1]
    if last in {tail, singular}:
        stripped = "".join(parts[:-1])
        if stripped:
            return _lower_first(stripped)
        return fallback or operation_name
    if len(parts) == 1:
        return parts[0]
    return fallback or operation_name


def _namespace_entry(route: RouteIR, operation_name: str, route_index: int) -> _NamespaceEntry:
    segments = _literal_route_segments(route.path)
    ends_with_param = _route_ends_with_param(route.path)
    namespace_tail = segments[-1] if segments else None
    heuristic = _method_verb(route.method, ends_with_param)
    verb = heuristic or _derive_verb(operation_name, namespace_tail, route.method, ends_with_param)

    if route.method.upper() == "POST" and len(segments) > 1 and not ends_with_param:
        handler_verb = _derive_verb(operation_name, namespace_tail, route.method, ends_with_param)
        if handler_verb != "create" and handler_verb != operation_name:
            verb = handler_verb

    return {
        "route_index": route_index,
        "segments": segments,
        "verb": _safe_ident(verb),
        "operation_name": operation_name,
    }


def _route_namespace_tree(ir: AppIR, route_names: dict[int, str]) -> _NamespaceNode:
    root = _new_namespace_node()
    for i, route in enumerate(ir.routes):
        entry = _namespace_entry(route, route_names[i], i)
        cursor = root
        for segment in entry["segments"]:
            cursor = cursor["children"].setdefault(segment, _new_namespace_node())

        key = entry["verb"]
        if key in cursor["leaves"] or key in cursor["children"]:
            key = _safe_ident(_camel_case(_split_camel(entry["operation_name"])))
        key = _unique_namespace_key(key, set(cursor["leaves"]) | set(cursor["children"]))
        entry["verb"] = key
        cursor["leaves"][key] = entry
    return root


def _unique_namespace_key(candidate: str, used: set[str]) -> str:
    if candidate not in used and not _is_reserved(candidate):
        return candidate
    base = candidate if not _is_reserved(candidate) else f"{candidate}_"
    i = 2
    while True:
        suffixed = f"{base}_{i}"
        if suffixed not in used:
            return suffixed
        i += 1


def _flatten_namespace_entries(root: _NamespaceNode) -> dict[int, _NamespaceEntry]:
    out: dict[int, _NamespaceEntry] = {}

    def visit(node: _NamespaceNode) -> None:
        for child in node["children"].values():
            visit(child)
        for entry in node["leaves"].values():
            out[entry["route_index"]] = entry

    visit(root)
    return out


def _unique_route_name(candidate: str, used: set[str]) -> str:
    if candidate not in used and not _is_reserved(candidate):
        return candidate
    base = candidate if not _is_reserved(candidate) else f"{candidate}_"
    i = 2
    while True:
        suffixed = f"{base}_{i}"
        if suffixed not in used:
            return suffixed
        i += 1


def _module_prefixed(full_key: str) -> str:
    head, _, tail = full_key.rpartition(".")
    prefix = head.rsplit(".", 1)[-1] if head else ""
    return _safe_ident(_pascal(prefix) + tail) if prefix else _safe_ident(tail)


def _pascal(name: str) -> str:
    return "".join(
        part[:1].upper() + part[1:] for part in name.replace("-", "_").split("_") if part
    )


_TS_FILE_SUFFIXES = {".ts", ".tsx", ".mts", ".cts"}


def write(ir: AppIR, out: Path) -> None:
    if out.suffix in _TS_FILE_SUFFIXES:
        raise ValueError(
            "Dyadpy now generates an optimized client directory, not a single .ts file. "
            f"Use a directory path such as {out.with_suffix('').as_posix()!r}.",
        )

    files = render(ir)
    tmp = out.parent / f".{out.name}.tmp"
    backup = out.parent / f".{out.name}.bak"
    shutil.rmtree(tmp, ignore_errors=True)
    shutil.rmtree(backup, ignore_errors=True)
    tmp.mkdir(parents=True, exist_ok=True)
    for rel, content in files.items():
        target = tmp / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")

    out.parent.mkdir(parents=True, exist_ok=True)
    try:
        if out.exists():
            out.replace(backup)
        tmp.replace(out)
    except Exception:
        if backup.exists() and not out.exists():
            backup.replace(out)
        raise
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
        shutil.rmtree(backup, ignore_errors=True)


# ---- type rendering ----


def _render_type(
    schema: Any,
    name_map: dict[str, str] | None = None,
    *,
    indent: str = "",
) -> str:
    if schema is None:
        return "void"
    if not isinstance(schema, dict):
        return "unknown"
    s = cast("dict[str, Any]", schema)
    if not s:
        return "JsonValue"

    if "$ref" in s:
        raw = str(s["$ref"]).rsplit("/", 1)[-1]
        if name_map is not None and raw in name_map:
            return name_map[raw]
        return _safe_ident(raw)
    if "const" in s:
        return json.dumps(s["const"])
    if "enum" in s:
        return _render_union([json.dumps(v) for v in cast("list[Any]", s["enum"])], indent=indent)
    if "oneOf" in s:
        return _render_union(
            [_render_type(x, name_map, indent=indent) for x in s["oneOf"]],
            indent=indent,
        )
    if "anyOf" in s:
        return _render_union(
            [_render_type(x, name_map, indent=indent) for x in s["anyOf"]],
            indent=indent,
        )
    if "allOf" in s:
        return " & ".join(_render_type(x, name_map, indent=indent) for x in s["allOf"])

    t: Any = s.get("type")
    if isinstance(t, list):
        # Pylance flags list contents as Unknown without the cast; mypy thinks
        # the cast is redundant. Side with Pylance — it's what shows in the editor.
        ts = cast("list[Any]", t)  # type: ignore[redundant-cast]
        rest = {k: v for k, v in s.items() if k != "type"}
        return _render_union(
            [_render_type({"type": x, **rest}, name_map, indent=indent) for x in ts],
            indent=indent,
        )

    if t == "string":
        return "Blob" if s.get("format") == "binary" else "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        if "prefixItems" in s:
            return (
                "["
                + ", ".join(_render_type(x, name_map, indent=indent) for x in s["prefixItems"])
                + "]"
            )
        items = s.get("items")
        inner = _render_type(items, name_map, indent=indent) if items else "unknown"
        return f"Array<{inner}>"
    if t == "object" or "properties" in s or "additionalProperties" in s:
        props = cast("dict[str, Any]", s.get("properties") or {})
        required_raw = cast("list[Any]", s.get("required") or [])
        required: set[str] = {_to_camel(str(k)) for k in required_raw}
        additional = s.get("additionalProperties")
        if not props and additional is not None and additional is not False:
            if additional is True or additional == {}:
                return "JsonObject"
            return f"Record<string, {_render_type(additional, name_map, indent=indent)}>"
        if not props:
            return "JsonObject"
        return _render_object(props, required, name_map, indent=indent)

    return "unknown"


def _uses_json_types(ir: AppIR) -> bool:
    for schema in ir.components.values():
        if _schema_uses_json_types(schema):
            return True
    for route in ir.routes:
        if route.response is not None and _schema_uses_json_types(route.response):
            return True
        if route.event_schema is not None and _schema_uses_json_types(route.event_schema):
            return True
        for param in route.params:
            if _schema_uses_json_types(param.schema):
                return True
        for error in route.raises:
            if _schema_uses_json_types(error.schema):
                return True
    return False


def _schema_uses_json_types(schema: Any) -> bool:
    if schema == {}:
        return True
    if isinstance(schema, list):
        return any(_schema_uses_json_types(item) for item in schema)
    if not isinstance(schema, dict):
        return False
    s = cast("dict[str, Any]", schema)
    if s.get("type") == "object" or "properties" in s or "additionalProperties" in s:
        props = cast("dict[str, Any]", s.get("properties") or {})
        additional = s.get("additionalProperties")
        if not props and (additional is None or additional is True or additional == {}):
            return True
        if additional is True or additional == {}:
            return True
    return any(_schema_uses_json_types(value) for value in s.values())


def _render_object(
    props: dict[str, Any],
    required: set[str],
    name_map: dict[str, str] | None,
    *,
    indent: str,
) -> str:
    inner_indent = indent + "  "
    field_strs: list[str] = []
    for key, child in props.items():
        ts_key = _to_camel(str(key))
        opt = "" if ts_key in required else "?"
        rendered = _render_type(child, name_map, indent=inner_indent)
        field_strs.append(f"{_safe_key(ts_key)}{opt}: {rendered}")

    inline_candidate = "{ " + "; ".join(field_strs) + " }"
    if (
        len(field_strs) <= _INLINE_FIELDS
        and len(indent) + len(inline_candidate) <= _INLINE_LINE_BUDGET
        and "\n" not in inline_candidate
    ):
        return inline_candidate

    lines = ["{"]
    for line in field_strs:
        lines.append(f"{inner_indent}{line};")
    lines.append(f"{indent}}}")
    return "\n".join(lines)


def _render_union(terms: list[str], *, indent: str) -> str:
    """Inline ``A | B | C`` for short unions; multi-line for long ones."""
    inline = " | ".join(terms)
    if (
        len(terms) <= _INLINE_UNION_TERMS
        and len(indent) + len(inline) <= _INLINE_LINE_BUDGET
        and "\n" not in inline
    ):
        return inline
    inner = indent + "  "
    return "\n" + "\n".join(f"{inner}| {t}" for t in terms)


def _render_method_signature(
    route: RouteIR,
    name_map: dict[str, str],
    route_name: str,
    *,
    indent: str = "  ",
) -> str:
    args_type, args_optional = _render_args_type(route.params, name_map, indent=indent)
    return_type = _render_return_type(route, name_map)
    if args_type is None:
        return f"{route_name}(opts?: CallOptions): {return_type};"

    inline = (
        f"{route_name}(args{'?' if args_optional else ''}: {args_type}, opts?: CallOptions): "
        f"{return_type};"
    )
    if "\n" not in inline and len(inline) <= _INLINE_LINE_BUDGET:
        return inline

    continuation = indent + "  "
    wrapped_args_type, _ = _render_args_type(route.params, name_map, indent=continuation)
    assert wrapped_args_type is not None
    return (
        f"{route_name}(\n"
        f"{continuation}args{'?' if args_optional else ''}: {wrapped_args_type},\n"
        f"{continuation}opts?: CallOptions,\n"
        f"{indent}): {return_type};"
    )


def _render_args_type(
    params: list[ParamIR],
    name_map: dict[str, str],
    *,
    indent: str,
) -> tuple[str | None, bool]:
    if not params:
        return None, True
    props: dict[str, Any] = {}
    required: set[str] = set()
    all_optional = True
    for p in params:
        if p.required:
            all_optional = False
        ts_name = _to_camel(p.name)
        if p.required:
            required.add(ts_name)
        props[ts_name] = p.schema
    return _render_object(props, required, name_map, indent=indent), all_optional


def _render_return_type(route: RouteIR, name_map: dict[str, str]) -> str:
    if route.streams:
        event = (
            _render_type(route.event_schema, name_map, indent="  ")
            if route.event_schema
            else "unknown"
        )
        return f"AsyncIterable<{event}>"
    data = _render_type(route.response, name_map, indent="  ") if route.response else "void"
    if route.raises:
        err = _render_error_union(route.raises, name_map, indent="  ")
        return f"Promise<Result<{data}, {err}>>"
    return f"Promise<{data}>"


def _render_error_union(raises: list[Any], name_map: dict[str, str], *, indent: str) -> str:
    return _render_union(
        [name_map.get(e.name, _safe_ident(e.name)) for e in raises],
        indent=indent,
    )


def _render_route_descriptor(
    route: RouteIR,
    route_name: str,
    namespace: _NamespaceEntry,
    *,
    indent: str,
    components: dict[str, dict[str, Any]],
) -> str:
    parts = [
        f"method: {json.dumps(route.method)}",
        f"path: {json.dumps(route.path)}",
        f"name: {json.dumps(route_name)}",
        "segments: " + json.dumps(namespace["segments"]),
        f"verb: {json.dumps(namespace['verb'])}",
    ]
    if route.params:
        parts.append(_render_param_descriptor_list(route.params, indent=indent))
    if route.streams:
        parts.append("streams: true")
    if route.raises:
        parts.append("result: true")
    if route.binary_body:
        parts.append("binaryBody: true")
    if route.binary_response:
        parts.append("binaryResponse: true")
    if route.form_body:
        parts.append("formBody: true")

    request_opaque = _collect_request_opaque_paths(route, components)
    if request_opaque:
        parts.append(f"opaqueRequestPaths: {json.dumps(request_opaque)}")
    response_opaque = _collect_response_opaque_paths(route, components)
    if response_opaque:
        parts.append(f"opaqueResponsePaths: {json.dumps(response_opaque)}")

    inline = indent + "{ " + ", ".join(parts) + " }"
    if "\n" not in inline and len(inline) <= _INLINE_LINE_BUDGET:
        return inline

    inner = indent + "  "
    lines = [indent + "{"]
    for p in parts:
        lines.append(f"{inner}{p},")
    lines.append(indent + "}")
    return "\n".join(lines)


# ---- Opaque path collection ------------------------------------------------
# JSON Schema walker that locates property paths whose declared type is an
# unconstrained object (``dict[str, Any]`` / ``JsonObject``). The TS runtime
# uses these paths to skip the snake_case <-> camelCase rename inside those
# subtrees so user-defined JSON payloads (e.g. ``RuleVersion.definition``)
# round-trip unchanged. Paths use camelCase property names — they're applied
# AFTER property renaming.


def _collect_response_opaque_paths(
    route: RouteIR,
    components: dict[str, dict[str, Any]],
) -> list[str]:
    """Opaque paths for the response payload (relative to the wire JSON).

    For routes that return ``Result<T, E>`` (``raises`` is non-empty), paths
    are prefixed with ``data.`` because the success envelope wraps ``T`` under
    ``data``.
    """
    if route.streams or route.binary_response:
        return []
    schema = route.response
    if schema is None:
        return []
    paths: list[str] = []
    _walk_for_opaque(schema, components, prefix="", out=paths, seen=set())
    if not paths:
        return []
    if route.raises:
        # Result success envelope wraps the typed payload under ``data``.
        return [f"data.{p}" if p else "data" for p in paths]
    return paths


def _collect_request_opaque_paths(
    route: RouteIR,
    components: dict[str, dict[str, Any]],
) -> list[str]:
    """Opaque paths for the request body (relative to the wire JSON).

    Embedded body params are nested under their alias on the wire; non-embed
    single-body params occupy the payload root.
    """
    if route.binary_body or route.form_body:
        return []
    body_params = [p for p in route.params if p.location == "body"]
    if not body_params:
        return []
    out: list[str] = []
    for param in body_params:
        prefix = param.alias if param.embed else ""
        _walk_for_opaque(param.schema, components, prefix=prefix, out=out, seen=set())
    return out


def _walk_for_opaque(
    schema: Any,
    components: dict[str, dict[str, Any]],
    *,
    prefix: str,
    out: list[str],
    seen: set[str],
) -> None:
    if not isinstance(schema, dict):
        return
    s = cast("dict[str, Any]", schema)

    if "$ref" in s:
        name = str(s["$ref"]).rsplit("/", 1)[-1]
        # Per-branch cycle guard — the same component can appear under
        # different prefixes, so we track refs by name within the current walk.
        if name in seen:
            return
        target = components.get(name)
        if target is None:
            return
        _walk_for_opaque(target, components, prefix=prefix, out=out, seen={*seen, name})
        return

    for combinator in ("oneOf", "anyOf", "allOf"):
        branches = s.get(combinator)
        if isinstance(branches, list):
            for branch in branches:
                _walk_for_opaque(branch, components, prefix=prefix, out=out, seen=seen)
            return

    t: Any = s.get("type")
    if isinstance(t, list):
        rest = {k: v for k, v in s.items() if k != "type"}
        for branch_t in t:
            _walk_for_opaque(
                {**rest, "type": branch_t},
                components,
                prefix=prefix,
                out=out,
                seen=seen,
            )
        return

    if t == "array":
        items = s.get("items")
        if items:
            # Array elements share the parent path — opaque paths are property-
            # relative, not index-relative.
            _walk_for_opaque(items, components, prefix=prefix, out=out, seen=seen)
        return

    if t == "object" or "properties" in s or "additionalProperties" in s:
        props = cast("dict[str, Any]", s.get("properties") or {})
        additional = s.get("additionalProperties")
        if not props:
            # No declared properties — this matches ``JsonObject`` (additionalProperties
            # absent, True, or {}) and ``dict[str, Any]``. ``additionalProperties: False``
            # represents an empty closed object and is not opaque.
            if additional is not False and prefix:
                out.append(prefix)
            return
        for raw_name, child in props.items():
            camel_name = _to_camel(str(raw_name))
            child_prefix = f"{prefix}.{camel_name}" if prefix else camel_name
            _walk_for_opaque(child, components, prefix=child_prefix, out=out, seen=seen)
        if isinstance(additional, dict):
            _walk_for_opaque(additional, components, prefix=prefix, out=out, seen=seen)
        return


def _render_param_descriptor_list(params: list[ParamIR], *, indent: str) -> str:
    # `indent` is the outer descriptor's indent; `params:` sits one nesting in.
    items = [_render_param_descriptor(p) for p in params]
    inline = "params: [" + ", ".join(items) + "]"
    if len(indent) + 2 + len(inline) <= _INLINE_LINE_BUDGET:
        return inline
    item_indent = indent + "    "
    close_indent = indent + "  "
    return (
        "params: [\n" + ",\n".join(f"{item_indent}{item}" for item in items) + f",\n{close_indent}]"
    )


def _render_param_descriptor(p: ParamIR) -> str:
    parts = [
        f"name: {json.dumps(_to_camel(p.name))}",
        f"alias: {json.dumps(p.alias)}",
        f"in: {json.dumps(p.location)}",
    ]
    if p.embed:
        parts.append("embed: true")
    return "{ " + ", ".join(parts) + " }"


_IDENT_RE = re.compile(r"[^A-Za-z0-9_]")
_SAFE_KEY_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _safe_ident(name: str) -> str:
    cleaned = _IDENT_RE.sub("_", name)
    if cleaned and cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned or "_"


def _safe_key(key: str) -> str:
    if _SAFE_KEY_RE.match(key) and not keyword.iskeyword(key):
        return key
    return json.dumps(key)
