"""Polyglot client codegen — Swift and Kotlin renderers off the same IR.

These are *minimal* renderers: shared structs become structs/data classes,
routes become methods on a generated ``Api`` type. Tagged unions, streaming
helpers, and per-language idioms (async/await, Result types) are emitted
where the language has a natural primitive.

Scope: enough to make Tythe usable from Swift and Kotlin without writing
the wire protocol by hand. Not full feature parity with the TS codegen.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, cast

from tythe.ir import AppIR, RouteIR

# ---------- Swift ----------


def render_swift(ir: AppIR) -> str:
    parts: list[str] = [
        "// AUTO-GENERATED by `tythe`. Do not edit by hand.\n",
        "import Foundation\n\n",
    ]
    for name, schema in sorted(ir.components.items()):
        parts.append(_swift_struct(name.rsplit(".", 1)[-1], schema))
    parts.append("public struct Api {\n")
    parts.append("    public let baseURL: URL\n")
    parts.append("    public init(baseURL: URL) { self.baseURL = baseURL }\n\n")
    for route in ir.routes:
        parts.append(_swift_method(route))
    parts.append("}\n")
    return "".join(parts)


def write_swift(ir: AppIR, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_swift(ir), encoding="utf-8")


def _swift_struct(name: str, schema: dict[str, Any]) -> str:
    props_any: Any = schema.get("properties")
    if not isinstance(props_any, dict):
        return ""
    props = cast("dict[str, Any]", props_any)
    lines = [f"public struct {_swift_ident(name)}: Codable {{\n"]
    for field_name, child in props.items():
        lines.append(f"    public let {_swift_ident(field_name)}: {_swift_type(child)}\n")
    lines.append("}\n\n")
    return "".join(lines)


def _swift_method(route: RouteIR) -> str:
    name = _swift_ident(_to_camel(route.name))
    return (
        f"    public func {name}() async throws -> Data {{\n"
        f'        let url = baseURL.appendingPathComponent("{route.path}")\n'
        f"        var req = URLRequest(url: url)\n"
        f'        req.httpMethod = "{route.method}"\n'
        f"        let (data, _) = try await URLSession.shared.data(for: req)\n"
        f"        return data\n"
        f"    }}\n\n"
    )


def _swift_type(schema: Any) -> str:
    if not isinstance(schema, dict):
        return "AnyCodable"
    s = cast("dict[str, Any]", schema)
    t = s.get("type")
    if t == "string":
        return "String"
    if t in ("integer", "number"):
        return "Double"
    if t == "boolean":
        return "Bool"
    if t == "array":
        return f"[{_swift_type(s.get('items'))}]"
    if "$ref" in s:
        return _swift_ident(str(s["$ref"]).rsplit("/", 1)[-1])
    return "AnyCodable"


def _swift_ident(name: str) -> str:
    cleaned = "".join(c if c.isalnum() or c == "_" else "_" for c in name)
    return cleaned or "_"


# ---------- Kotlin ----------


def render_kotlin(ir: AppIR, *, package: str = "com.tythe.generated") -> str:
    parts: list[str] = [
        "// AUTO-GENERATED by `tythe`. Do not edit by hand.\n",
        f"package {package}\n\n",
        "import kotlinx.serialization.Serializable\n\n",
    ]
    for name, schema in sorted(ir.components.items()):
        parts.append(_kotlin_data_class(name.rsplit(".", 1)[-1], schema))
    parts.append("class Api(private val baseUrl: String) {\n")
    for route in ir.routes:
        parts.append(_kotlin_method(route))
    parts.append("}\n")
    return "".join(parts)


def write_kotlin(ir: AppIR, out: Path, *, package: str = "com.tythe.generated") -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_kotlin(ir, package=package), encoding="utf-8")


def _kotlin_data_class(name: str, schema: dict[str, Any]) -> str:
    props_any: Any = schema.get("properties")
    if not isinstance(props_any, dict):
        return ""
    props = cast("dict[str, Any]", props_any)
    fields_out = [f"    val {_kotlin_ident(k)}: {_kotlin_type(v)}" for k, v in props.items()]
    return (
        f"@Serializable\ndata class {_kotlin_ident(name)}(\n" + ",\n".join(fields_out) + "\n)\n\n"
    )


def _kotlin_method(route: RouteIR) -> str:
    name = _kotlin_ident(_to_camel(route.name))
    return f'    suspend fun {name}(): String = TODO("HTTP {route.method} {route.path}")\n'


def _kotlin_type(schema: Any) -> str:
    if not isinstance(schema, dict):
        return "Any"
    s = cast("dict[str, Any]", schema)
    t = s.get("type")
    if t == "string":
        return "String"
    if t == "integer":
        return "Long"
    if t == "number":
        return "Double"
    if t == "boolean":
        return "Boolean"
    if t == "array":
        return f"List<{_kotlin_type(s.get('items'))}>"
    if "$ref" in s:
        return _kotlin_ident(str(s["$ref"]).rsplit("/", 1)[-1])
    return "Any"


def _kotlin_ident(name: str) -> str:
    cleaned = "".join(c if c.isalnum() or c == "_" else "_" for c in name)
    return cleaned or "_"


def _to_camel(name: str) -> str:
    if "_" not in name:
        return name
    head, *rest = name.split("_")
    return head + "".join(p[:1].upper() + p[1:] for p in rest if p)
